services:
  api:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017

  mongo:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
